# Use the official mysql base image
FROM mysql:latest

# Set environment variable for API key expiration
ENV API_KEY_EXPIRATION=600

# Copy the initialization script into the container
COPY run_at_start.sh /run_at_start.sh
RUN chmod +x /run_at_start.sh
#COPY init.sh /docker-entrypoint-initdb.d/init.sh
#RUN chmod +x /docker-entrypoint-initdb.d/init.sh
#RUN chown -R mysql:mysql /docker-entrypoint-initdb.d/

# No need to specify ENTRYPOINT and CMD again, as the image already has them
ENTRYPOINT ["/run_at_start.sh"]
