# Use the lightweight MariaDB Alpine image
FROM mariadb:latest

# Copy the memopry optimized my.cnf configuration file
COPY my.cnf /etc/mysql/my.cnf

# Copy the initialization script into the container
COPY run_at_start.sh /run_at_start.sh
RUN chmod +x /run_at_start.sh

# Expose MariaDB port
EXPOSE 3306

# Set environment variable for API key expiration.  Can be set at runtime.
ENV API_KEY_EXPIRATION=600

# Run script to dynamically generate init.sql with env variables
ENTRYPOINT ["/run_at_start.sh"]