# Use an official Python runtime as the base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the application files to the container
COPY /app /app

# Copy the startup script
RUN chmod +x /app/run_at_start.sh

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port (default: 5000)
EXPOSE 5000

# Use the shell script to start the Gunicorn server with environment variables
CMD ["/app/run_at_start.sh"]